### ISSUE TITLE
Implementation is inside header file

### ISSUE THREAD

**Issue by Mart-Bogdan** [mortezaipo/gtwili#1]
All functions should be implemented in .c files, and .h file should have only a definition.

Unless functions are declared as static, but that would bloat .c -> .o files that included this header.

P.S. haven't found implementation of create_bigbutton function, which is mentioned in README.

**Comment by mortymacs** [comment]
Dear Bogdan Mart,

Thanks for reporting. I'll fix the code and update the README file very soon.

**Comment by mortymacs** [comment]
Dear Bogdan Mart,

I just updated the repo. Please have a look at the [`demo.c`](https://github.com/mortymacs/fawn/blob/main/demo.c) file.
I'll add Doxygen in the future and also about decoupling the header and source files I was thinking the header-only would have easy installation for the end-user. What's your idea? we can decouple it if you think it's necessary.

Cheers,
Mort

**Comment by Mart-Bogdan** [comment]
Hello. Thanks for updating the demo. Sorry for not checking it earlier.

**Comment by Mart-Bogdan** [comment]
> I was thinking the header-only would have easy installation for the end-user.

I generally agree with that. But currently, if header is include in more than one `.c` file it would produce linkage errors.

AFAIK header inly libraries are using some tricks to make it work. I'm not currently sure what exactly.

**Comment by mortymacs** [comment]
> > I was thinking the header-only would have easy installation for the end-user.
> 
> I generally agree with that. But currently, if header is include in more than one `.c` file it would produce linkage errors.
> 
> AFAIK header inly libraries are using some tricks to make it work. I'm not currently sure what exactly.

Do you have any samples that I can reproduce? because it has included guard to avoid being included more than once.
